# Generated by Django 6.1.1 on 2026-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPerecedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio_regular', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_vencimiento', models.IntegerField()),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
